services:
  - type: web
    name: sig-monolito
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: "production"
    autoDeploy: true
