services:
  - type: web
    name: sig-monolito
    env: python
    plan: free
    # Build: instala Python y Node dependencies
    buildCommand: |
      cd backend && pip install --upgrade pip && pip install -r requirements.txt
      cd ../frontend && npm install
    # Start: ejecuta el script que levanta backend y frontend
    startCommand: "./start-all.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: NODE_ENV
        value: "development"
    autoDeploy: true
