services:
  - type: web
    name: sig-monolito
    env: python
    plan: free

    buildCommand: "./start-all.sh"
    startCommand: "./start-all.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: NODE_ENV
        value: "development"
    autoDeploy: true