services:
  # ---------------------------
  # Backend FastAPI
  # ---------------------------
  - type: web
    name: fastapi-app
    rootDir: backend
    env: python
    pythonVersion: 3.11.9
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      prisma generate
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false

  # ---------------------------
  # Frontend Next.js
  # ---------------------------
  - type: web
    name: nextjs-app
    rootDir: frontend
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://fastapi-app.onrender.com
