services:
  - type: web
    name: sig-monolito
    env: python
    plan: free
    # Build: instalar dependencias desde la carpeta correcta
    buildCommand: "pip install --upgrade pip && pip install -r backend/requirements.txt && cd frontend && npm install"
    startCommand: "./start-all.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: NODE_ENV
        value: "development"
    autoDeploy: true